### ISSUE TITLE
Unsavory API methods

### ISSUE THREAD

**Issue by laughinghan** [mathquill/mathquill#456]
- `.html()`: can we get rid of this? I gave up on the thing about MathQuill's HTML being semantic.
- `.keystroke('Ctrl-Home Del')` and `.typedText('/2')`: this turns changes that otherwise would just be typist interaction changes into API-compatibility changes; like, code that relies on backspacing twice to delete commands get totally broken by #453, as we can see in its tests changes. Instead `.moveDir()`, `.deleteDir()`, `.selectDir()` should probably exposed? But what about implementing a virtual keyboard, we want backspace there to behave exactly like a real backspace key would, including "interaction" changes to it, right?

Present but undocumented:
- `.text()`: was originally meant to be more "human-readable" than LaTeX, but then I tried using MathQuill in a project using SymPy so I changed e.g. `^` to `**` so that the results of `.text()` could be passed to [`sympify()`](http://docs.sympy.org/dev/modules/core.html#id1). This probably shouldn't exist at all, instead there should be a getter for the well-specified, more-human-readable-than-LaTeX [AsciiMath](http://asciimath.org/) format, and a separate getter (if at all) for `sympify()` format.
- `.innerFields`: this should be a method, right? Non-method fields seem bad for forward-compat.

**Comment by ampled** [comment]
An AsciiMath-API would be huge for Python-related projects.

**Comment by jwmerrill** [comment]
I'd be tempted to leave translating latex into AsciiMath or sympy format or
whatever to a different project, unless we think we have some advantage on
this front.

**Comment by laughinghan** [comment]
@ampled

> An AsciiMath-API would be huge for Python-related projects.

Wait, why? Is AsciiMath widely used in Python-related projects? I don't remember noticing its use in any major projects.

**Comment by laughinghan** [comment]
> I'd be tempted to leave translating latex into AsciiMath or sympy format or
whatever to a different project, unless we think we have some advantage on
this front.

The LaTeX format we output isn't super easy to parse. The advantage of doing it internally is we can traverse the tree instead of re-parsing the LaTeX. (It would possibly be nice to expose something about the tree, even something high-level like traversing the tree, but I'm pretty scared of committing to the current structure of the tree.)

**Comment by kschaefe** [comment]
Well, can't we change the tree structure during an interface version change?  I thought that was the goal of #459.

**Comment by laughinghan** [comment]
Right, we wouldn't be committing to the tree structure in that it'd be
impossible to change it, but it'd still be more difficult to change it if
we exposed it, shimming the old structure for old interface versions would
likely be nontrivial since it's not localized, it involves many commands.

Han

**Comment by ampled** [comment]
@laughinghan SymPy uses a syntax similar to asciimath

**Comment by laughinghan** [comment]
@ampled Ah, I see. You're talking about the syntax accepted by [`sympify()`](http://docs.sympy.org/dev/modules/core.html#id1), right? There's at least one major difference from AsciiMath, in SymPy exponents are `x**2`, in AsciiMath they're `x^2` (`x**2` is actually `x\ast 2`). I think they'd have to be separate output formats.

**Comment by Harrison-G** [comment]
@laughinghan @ampled SymPy can parse AsciiMath using `sympy.parsing.sympy_parser.parse_expr`, so the ability to output AsciiMath would be fantastic, covering more than just SymPy while still supporting it.

**Comment by jwmerrill** [comment]
@Harrison-G `sympy.parsing.sympy_parser.parse_expr` is designed to parse python expressions as output by SymPy, which is not the same as AsciiMath.

For example, the following expression appears as an example in the [AsciiMath docs](http://asciimath.org/#syntax): 

```
int_0^1 f(x)dx
```

Here's what happens when I try to parse it using the sympy parser:

```python
>>> parsing.sympy_parser.parse_expr('int_0^1 f(x)dx')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/parsing/sympy_parser.py", line 820, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/parsing/sympy_parser.py", line 733, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Symbol ('int_0' )^Integer (1 )Symbol ('f' )(Symbol ('x' ))Symbol ('dx' )
                                       ^
SyntaxError: invalid syntax
```

It would wonderful if there were better ways of sharing math expressions between different systems, but as far as I can tell, this is an unsolved problem--not just for mathquill, but for everyone.

**Comment by jwmerrill** [comment]
BTW, [Content MathML](https://en.wikipedia.org/wiki/MathML#Content_MathML) (distinguished from Presentation MathML) was designed to be an interchange format that could represent the semantics of mathematical expressions, instead of just their presentation. But last I knew, no one implements it.

LaTeX and AsciiMath are designed to represent presentation, rather than semantics, similar to Presentation MathML. As far as I know, math representation languages break down roughly into

1. Representations of the presentation of math, but not its semantics (Presentation MathML, LaTeX, AsciiMath)
2. Representations of the semantics of expressions that are specific to a single system (the syntax every programming language, including Mathematica and Python/Sympy)
3. Representations of the semantics of expressions that are designed to be generic and interchangeable across systems, but which nobody emits or accepts (Content MathML).

One way to tell the difference is to look at how something like `f(x+1)^2` is represented. There's basically only one way to present this, but semantically, it could either mean `pow(apply('f', add('x',1)), 2)` or `mul('f', pow(add('x', 1), 2)`.

Mathquill, which is a presentational rather than semantic system, doesn't distinguish between these two semantic possibilities, so it would be difficult or impossible for MathQuill to output any semantic representation that makes this distinction (e.g. the language that Sympy accepts as input).

**Comment by jwmerrill** [comment]
> `.html()`: can we get rid of this? I gave up on the thing about MathQuill's HTML being semantic.

I'd be okay with getting rid of this if it doesn't really work in practice. One reason to have something like this would be if mathquill could be run on the server so that the latex->html translation could happen there instead of on the client. But then, if you wanted the result to still be editable, mathquill would have to know how to parse the html that it outputs. Not being able to do that seems like a decent reason to not support this feature (yet).

Instead of parsing the html by reading every DOM node, another possibility would be to store the latex of an expression as an attribute on the expression root node. Then you could just run the latex parser on that if you needed to make an html block editable.

> `.keystroke('Ctrl-Home Del')` and `.typedText('/2')`: this turns changes that otherwise would just be typist interaction changes into API-compatibility changes; like, code that relies on backspacing twice to delete commands get totally broken by #453, as we can see in its tests changes. Instead `.moveDir()`, 
`.deleteDir()`, `.selectDir()` should probably exposed? But what about implementing a virtual keyboard, we want backspace there to behave exactly like a real backspace key would, including "interaction" changes to it, right?

I think that it's potentially useful to expose both sets of commands, and to then document that there is no guaranteed fixed relationship between them. If you need certain semantics, you should use the semantic API. If you need one-to-one correspondence with a physical keyboard, you should use the keystroke api.

> Present but undocumented:
> `.text()`: was originally meant to be more "human-readable" than LaTeX, but then I tried using MathQuill in a project using SymPy so I changed e.g. `^` to `**` so that the results of `.text()` could be passed to [`sympify()`](http://docs.sympy.org/dev/modules/core.html#id1). This probably shouldn't exist at all, instead there should be a getter for the well-specified, more-human-readable-than-LaTeX [AsciiMath](http://asciimath.org/) format, and a separate getter (if at all) for `sympify()` format.

For the reasons listed above, I think we should drop this feature. If other systems want to supply some semantics to presentation math, they should implement their own latex parser that does this. "That's hard to do well," [you say](https://github.com/sympy/sympy/wiki/Parsing)? Yes... yes it is.

If we heard demand for it, I'd be much more enthusiastic about adding the ability to emit Presentation MathML, since there is (should be?) a much closer correspondence between that, and what MathQuill already represents internally.

> `.innerFields`: this should be a method, right? Non-method fields seem bad for forward-compat.

Sure.

**Comment by laughinghan** [comment]
(To tie this back to the earlier discussion, `sympy.parsing.sympy_parser.parse_expr` is actually exactly what `sympify()` calls.)

And that's a great point about how the underlying basis of SymPy's syntax is completely different from that of LaTeX/AsciiMath/Presentation MathML.

**Comment by Harrison-G** [comment]
@jwmerrill Ah, I see. Thank you for clarifying.

**Comment by Upabjojr** [comment]
Hi people!

Is there any way MathQuill could output its expression tree as an clearly-arboreal data structure (such as a JSON object)? JSON objects would be great, because they can immediately be evaluated as Python dict/list objects.

MathQuill and SymPy could cooperate to add a reader/writer for an interchange format and make interaction easier.

SymPy currently supports Jupyter notebooks (notebook inside a browser) and renders LaTeX output expressions to HTML through MathJAX. I would love to see an interactive notebook where you can edit SymPy output expressions.

**Comment by laughinghan** [comment]
@Upabjojr: what a great idea! I've been working (on and off, unfortunately) on a format called "MathSON" for exactly this purpose! https://gist.github.com/laughinghan/4350e4438e6cfc951826

I'm pretty sure it's the future of MathQuill; while MathQuill will probably have built-in support for LaTeX for quite a while, instead of built-in support for the text format that SymPy expects vs the text format that Math.js expects vs algebra.js vs AsciiMath etc, those can just be converted to/from MathSON.

**Comment by Upabjojr** [comment]
> https://gist.github.com/laughinghan/4350e4438e6cfc951826

Nice.

> I'm pretty sure it's the future of MathQuill; while MathQuill will probably have built-in support for LaTeX for quite a while,

Is there currently any way to dump the JSON structure of the expression in MathQuill?

**Comment by laughinghan** [comment]
Well...no, not really, currently parsing LaTeX from MathQuill is the "blessed" usage. It should be straightforward to patch MathQuill to dump MathSON though.
