### ISSUE TITLE
Mathquill-0.10.1 jquery dependency is no longer 1.5.2?

### ISSUE THREAD

**Issue by TheWithz** [mathquill/mathquill#783]
I am using the quickstart.html for testing and I get this error when looking at the html. 
>mathquill.js:2330 Uncaught TypeError: this.container.prepend(...).on is not a function
>at Bare._.editablesTextareaEvents (file:///home/thewithz/lib/TheWithz.Github.io/mathquill0.10.1/mathquill.js:2330:6)
>at Bare._.__mathquillify (file:///home/thewithz/lib/TheWithz.Github.io/mathquill0.10.1/mathquill.js:1051:25)
>at Bare._.__mathquillify (file:///home/thewithz/lib/TheWithz.Github.io/mathquill0.10.1/mathquill.js:2827:29)
>at Function.MQ.(anonymous function) [as MathField](file:///home/thewithz/lib/TheWithz.Github.io/mathquill-0.10.1/mathquill.js:1133:30)
>at file:///home/thewithz/lib/TheWithz.Github.io/pittMathTesting/test.html:25:26
>_.editablesTextareaEvents @ mathquill.js:2330
>_.__mathquillify @ mathquill.js:1051
>_.__mathquillify @ mathquill.js:2827
>MQ.(anonymous function) @ mathquill.js:1133
>(anonymous) @ test.html:25

However, If I use jquery dependency 3.2.1 then I no longer have this error and the quickstart file works as intended. I read the 0.9->0.10 migration guide and didn't see anything that might explain this behavior.

**Comment by TheWithz** [comment]
To follow up, out of all the jquery versions I tested, 1.7.0 was the lowest dependency that worked correctly.
